language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pytest
  - pycodestyle . --exclude .git,__pycache__,realthunder_kicad_parser,venv,.pip --max-line-length=120